title : JULIO SELEMANI SENGI
logo: img/julio5.png
description: Développeur | Architecte Systèmes | Chef de Projet | Intégrateur IA & Solutions Digitales
show_downloards: true  
them: jekyll-them-minimal
lang : fr 
